name: simple_sync
description: Simple reminder syncing app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cloud_firestore: ^3.1.13
  datetime_picker_formfield: ^2.0.0
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.6.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  uuid: ^3.0.6

dev_dependencies:
  analyzer: ^3.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.1.6
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
