// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVgmeHgyuN7fLpFYkUyeRP4pQ_IzBLyY',
    appId: '1:636233175718:web:3b7b1dc6125de14becda67',
    messagingSenderId: '636233175718',
    projectId: 'simple-sync-58ca9',
    authDomain: 'simple-sync-58ca9.firebaseapp.com',
    storageBucket: 'simple-sync-58ca9.appspot.com',
    measurementId: 'G-6ERPPEYEQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC145LuOjCNUuG_g1hkdAus9PfcMAMGVOY',
    appId: '1:636233175718:android:b1d24b2119f5da39ecda67',
    messagingSenderId: '636233175718',
    projectId: 'simple-sync-58ca9',
    storageBucket: 'simple-sync-58ca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8kT9Yz1qtZZjuPj5AqX1kN_uTGB65U8',
    appId: '1:636233175718:ios:5b84aae88e14d0d5ecda67',
    messagingSenderId: '636233175718',
    projectId: 'simple-sync-58ca9',
    storageBucket: 'simple-sync-58ca9.appspot.com',
    androidClientId: '636233175718-4idhhg26f48ekc8fn4sfe9020m4fe7kp.apps.googleusercontent.com',
    iosClientId: '636233175718-hgin71vmcdd956vokeal12ls1jblq2h0.apps.googleusercontent.com',
    iosBundleId: 'com.brandontrautmann.simplesync.simple-sync',
  );
}
