name: Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-ios:
    defaults:
      run:
        shell: bash
        working-directory: simple_sync/ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.4'
          channel: stable
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Bundle install
        run: bundle install
      - name: Calculate version name
        id: calculate_version_name
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
      - name: Deploy iOS to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER }}
          VERSION_NAME: ${{ steps.calculate_version_name.outputs.version }}
          BUILD_NUMBER: ${{ steps.calculate_version_name.outputs.increment }}
        run: bundle exec fastlane deploy
      - name: Tag release
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: "git tag v${{ steps.calculate_version_name.outputs.version }} -a -m \"Updated to ${{ steps.calculate_version_name.outputs.version }}\""
      - run: "git push --tags"
